#!/usr/bin/env python3
"""Generate movies-data.js for the multi-actor checklist."""
import json

def m(id, year, en, ko, genre, note=""):
    return {"id": id, "year": year, "en": en, "ko": ko, "genre": genre, "note": note}

# --- DENZEL (from existing) ---
denzel = [
m("carbon-copy",1981,"Carbon Copy","카본 카피","코미디","장편 데뷔작"),
m("soldiers-story",1984,"A Soldier's Story","솔저 스토리","드라마/미스터리"),
m("power",1986,"Power","파워","드라마","리처드 기어의 파워로도 표기"),
m("cry-freedom",1987,"Cry Freedom","자유의 절규","전기/드라마","오스카 남우조연 후보"),
m("for-queen-and-country",1988,"For Queen and Country","최후의 총성","드라마"),
m("mighty-quinn",1989,"The Mighty Quinn","형사 퀸","미스터리"),
m("glory",1989,"Glory","영광의 깃발","전쟁/드라마","오스카 남우조연상 수상"),
m("heart-condition",1990,"Heart Condition","하트 컨디션","코미디"),
m("mo-better-blues",1990,"Mo' Better Blues","모 베터 블루스","드라마/음악","스파이크 리 연출"),
m("mississippi-masala",1991,"Mississippi Masala","미시시피 마살라","로맨스/드라마"),
m("ricochet",1991,"Ricochet","닉크","액션/스릴러","한국 개봉명 닉크"),
m("malcolm-x",1992,"Malcolm X","말콤 X","전기/드라마","오스카 남우주연 후보"),
m("much-ado",1993,"Much Ado About Nothing","헛소동","코미디"),
m("pelican-brief",1993,"The Pelican Brief","펠리칸 브리프","스릴러"),
m("philadelphia",1993,"Philadelphia","필라델피아","드라마"),
m("crimson-tide",1995,"Crimson Tide","크림슨 타이드","액션/스릴러"),
m("virtuosity",1995,"Virtuosity","가상현실","SF/액션","일명 킬링 머신"),
m("devil-blue-dress",1995,"Devil in a Blue Dress","블루 데블","미스터리/느와르"),
m("courage-under-fire",1996,"Courage Under Fire","커리지 언더 파이어","전쟁/드라마"),
m("preachers-wife",1996,"The Preacher's Wife","프리쳐스 와이프","로맨스/코미디"),
m("fallen",1998,"Fallen","다크 엔젤","스릴러/공포","한국 개봉명 다크 엔젤"),
m("he-got-game",1998,"He Got Game","히 갓 게임","드라마/스포츠","스파이크 리 연출"),
m("the-siege",1998,"The Siege","비상계엄","액션/스릴러"),
m("bone-collector",1999,"The Bone Collector","본 콜렉터","스릴러"),
m("the-hurricane",1999,"The Hurricane","허리케인 카터","전기/드라마","오스카 남우주연 후보"),
m("remember-titans",2000,"Remember the Titans","리멤버 타이탄","스포츠/드라마"),
m("training-day",2001,"Training Day","트레이닝 데이","범죄/스릴러","오스카 남우주연상 수상"),
m("john-q",2002,"John Q.","존 큐","드라마/스릴러"),
m("antwone-fisher",2002,"Antwone Fisher","앤트원 피셔","드라마","감독·출연"),
m("out-of-time",2003,"Out of Time","아웃 오브 타임","스릴러"),
m("man-on-fire",2004,"Man on Fire","맨 온 파이어","액션/스릴러"),
m("manchurian-candidate",2004,"The Manchurian Candidate","맨추리안 캔디데이트","정치 스릴러"),
m("inside-man",2006,"Inside Man","인사이드 맨","범죄/스릴러","스파이크 리 연출"),
m("deja-vu",2006,"Déjà Vu","데자뷰","SF/액션"),
m("american-gangster",2007,"American Gangster","아메리칸 갱스터","범죄/드라마"),
m("great-debaters",2007,"The Great Debaters","그레이트 디베이터스","드라마","감독·출연"),
m("pelham-123",2009,"The Taking of Pelham 123","서브웨이 하이재킹: 펠햄 123","액션/스릴러"),
m("book-of-eli",2010,"The Book of Eli","일라이","액션/SF"),
m("unstoppable",2010,"Unstoppable","언스토퍼블","액션/스릴러"),
m("safe-house",2012,"Safe House","세이프 하우스","액션/스릴러"),
m("flight",2012,"Flight","플라이트","드라마","오스카 남우주연 후보"),
m("2-guns",2013,"2 Guns","투건스","액션/코미디"),
m("equalizer",2014,"The Equalizer","더 이퀄라이저","액션"),
m("magnificent-seven",2016,"The Magnificent Seven","매그니피센트 7","서부/액션"),
m("fences",2016,"Fences","펜스","드라마","감독·출연 · 오스카 남우주연 후보"),
m("roman-j-israel",2017,"Roman J. Israel, Esq.","로만 J 이스라엘, 에스콰이어","드라마","오스카 남우주연 후보"),
m("equalizer-2",2018,"The Equalizer 2","더 이퀄라이저 2","액션"),
m("little-things",2021,"The Little Things","더 리틀 띵스","범죄/스릴러"),
m("tragedy-macbeth",2021,"The Tragedy of Macbeth","맥베스의 비극","드라마","오스카 남우주연 후보 · Apple TV+"),
m("equalizer-3",2023,"The Equalizer 3","더 이퀄라이저 3","액션"),
m("gladiator-2",2024,"Gladiator II","글래디에이터 Ⅱ","역사/액션"),
m("highest-2-lowest",2025,"Highest 2 Lowest","천국부터 지옥까지","범죄/스릴러","스파이크 리 연출 · A24 / Apple TV+"),
]

matt = [
m("mystic-pizza",1988,"Mystic Pizza","미스틱 피자","로맨스/코미디","소역할"),
m("school-ties",1992,"School Ties","스쿨 타이즈","드라마"),
m("geronimo",1993,"Geronimo: An American Legend","제로니모","서부/드라마"),
m("courage-under-fire-md",1996,"Courage Under Fire","커리지 언더 파이어","전쟁/드라마"),
m("rainmaker",1997,"The Rainmaker","레인메이커","법정 드라마"),
m("good-will-hunting",1997,"Good Will Hunting","굿 윌 헌팅","드라마","오스카 각본상 · 남우주연 후보"),
m("saving-private-ryan",1998,"Saving Private Ryan","라이언 일병 구하기","전쟁"),
m("rounders",1998,"Rounders","라운더스","드라마"),
m("dogma",1999,"Dogma","도그마","코미디"),
m("talented-mr-ripley",1999,"The Talented Mr. Ripley","탤런티드 미스터 리플리","스릴러"),
m("legend-bagger-vance",2000,"The Legend of Bagger Vance","배거 밴스의 전설","스포츠/드라마"),
m("all-pretty-horses",2000,"All the Pretty Horses","올 더 프리티 호시스","서부/드라마"),
m("oceans-eleven",2001,"Ocean's Eleven","오션스 일레븐","범죄/코미디"),
m("bourne-identity",2002,"The Bourne Identity","본 아이덴티티","액션/스릴러"),
m("gerry",2002,"Gerry","게리","드라마"),
m("stuck-on-you",2003,"Stuck on You","스터크 온 유","코미디"),
m("bourne-supremacy",2004,"The Bourne Supremacy","본 슈프리머시","액션/스릴러"),
m("oceans-twelve",2004,"Ocean's Twelve","오션스 트웰브","범죄/코미디"),
m("brothers-grimm",2005,"The Brothers Grimm","브라더스 그림","판타지/어드벤처"),
m("syriana",2005,"Syriana","시리아나","정치 스릴러"),
m("the-departed",2006,"The Departed","디파티드","범죄/스릴러"),
m("good-shepherd",2006,"The Good Shepherd","굿 셰퍼드","스파이/드라마"),
m("oceans-thirteen",2007,"Ocean's Thirteen","오션스 서틴","범죄/코미디"),
m("bourne-ultimatum",2007,"The Bourne Ultimatum","본 얼티메이텀","액션/스릴러"),
m("informant",2009,"The Informant!","인포먼트!","코미디/드라마"),
m("invictus",2009,"Invictus","인빅터스","스포츠/드라마","오스카 남우조연 후보"),
m("green-zone",2010,"Green Zone","그린 존","액션/스릴러"),
m("hereafter",2010,"Hereafter","헤리어프터","드라마"),
m("true-grit",2010,"True Grit","트루 그릿","서부"),
m("adjustment-bureau",2011,"The Adjustment Bureau","애드저스트먼트 뷰로","SF/로맨스"),
m("contagion",2011,"Contagion","컨테이젼","스릴러"),
m("we-bought-a-zoo",2011,"We Bought a Zoo","우리는 동물원을 샀다","드라마/코미디"),
m("promised-land",2012,"Promised Land","프로미스드 랜드","드라마"),
m("elysium",2013,"Elysium","엘리시움","SF/액션"),
m("zero-theorem",2013,"The Zero Theorem","제로 정리","SF"),
m("monuments-men",2014,"The Monuments Men","모뉴먼츠 맨","전쟁/코미디"),
m("interstellar-md",2014,"Interstellar","인터스텔라","SF","조연"),
m("the-martian",2015,"The Martian","마션","SF","오스카 남우주연 후보"),
m("jason-bourne",2016,"Jason Bourne","제이슨 본","액션/스릴러"),
m("great-wall",2016,"The Great Wall","만리장성","액션/판타지"),
m("downsizing",2017,"Downsizing","다운사이징","SF/코미디"),
m("suburbicon",2017,"Suburbicon","서브어비콘","범죄/코미디"),
m("ford-v-ferrari",2019,"Ford v Ferrari","포드 V 페라리","스포츠/드라마"),
m("stillwater",2021,"Stillwater","스틸워터","드라마/스릴러"),
m("last-duel",2021,"The Last Duel","라스트 듀얼","역사/드라마"),
m("air",2023,"Air","에어","스포츠/드라마"),
m("oppenheimer-md",2023,"Oppenheimer","오펜하이머","전기/드라마"),
m("instigators",2024,"The Instigators","인스티게이터스","액션/코미디","Apple TV+"),
]

daniel = [
m("power-of-one",1992,"The Power of One","하나의 힘","드라마","장편 데뷔"),
m("kid-king-arthur",1995,"A Kid in King Arthur's Court","아더왕의 궁전","판타지/가족"),
m("elizabeth",1998,"Elizabeth","엘리자베스","역사/드라마"),
m("love-is-devil",1998,"Love Is the Devil","러브 이즈 더 데빌","전기/드라마"),
m("the-trench",1999,"The Trench","트렌치","전쟁"),
m("some-voices",2000,"Some Voices","섬 보이시스","드라마"),
m("i-dreamed-africa",2000,"I Dreamed of Africa","아프리카의 꿈","전기/드라마"),
m("tomb-raider",2001,"Lara Croft: Tomb Raider","툼레이더","액션/어드벤처"),
m("road-to-perdition",2002,"Road to Perdition","로드 투 퍼디션","범죄/드라마"),
m("sylvia",2003,"Sylvia","실비아","전기/드라마"),
m("the-mother",2003,"The Mother","마더","드라마"),
m("layer-cake",2004,"Layer Cake","레이어 케이크","범죄/스릴러"),
m("enduring-love",2004,"Enduring Love","인듀어링 러브","스릴러"),
m("the-jacket",2005,"The Jacket","더 재킷","스릴러"),
m("munich",2005,"Munich","뮌헨","스릴러/드라마"),
m("infamous",2006,"Infamous","인퍼머스","전기/드라마"),
m("casino-royale",2006,"Casino Royale","카지노 로얄","액션/스파이","007 데뷔"),
m("the-invasion",2007,"The Invasion","인베이젼","SF/스릴러"),
m("golden-compass",2007,"The Golden Compass","황금나침반","판타지"),
m("quantum-solace",2008,"Quantum of Solace","퀀텀 오브 솔러스","액션/스파이"),
m("defiance",2008,"Defiance","디파이언스","전쟁/드라마"),
m("flashbacks-fool",2008,"Flashbacks of a Fool","플래시백스 오브 어 풀","드라마"),
m("cowboys-aliens",2011,"Cowboys & Aliens","카우보이 & 에일리언","SF/서부"),
m("dream-house",2011,"Dream House","드림 하우스","스릴러"),
m("girl-dragon-tattoo",2011,"The Girl with the Dragon Tattoo","여자를 증오한 남자들","스릴러"),
m("skyfall",2012,"Skyfall","스카이폴","액션/스파이"),
m("spectre",2015,"Spectre","스펙터","액션/스파이"),
m("logan-lucky",2017,"Logan Lucky","로건 럭키","범죄/코미디"),
m("kings",2017,"Kings","킹스","드라마"),
m("knives-out",2019,"Knives Out","나이브스 아웃","미스터리/코미디"),
m("no-time-to-die",2021,"No Time to Die","노 타임 투 다이","액션/스파이","007 마지막"),
m("glass-onion",2022,"Glass Onion","글래스 어니언: 나이브스 아웃","미스터리/코미디","Netflix"),
m("queer",2024,"Queer","퀴어","드라마"),
m("wake-up-dead-man",2025,"Wake Up Dead Man","웨이크 업 데드 맨","미스터리","나이브스 아웃 3"),
]

tom_cruise = [
m("endless-love",1981,"Endless Love","엔드리스 러브","로맨스","소역할"),
m("taps",1981,"Taps","탭스","드라마"),
m("losin-it",1982,"Losin' It","루징 잇","코미디"),
m("the-outsiders",1983,"The Outsiders","아웃사이더","드라마"),
m("risky-business",1983,"Risky Business","리스키 비즈니스","코미디"),
m("all-right-moves",1983,"All the Right Moves","올 더 라이트 무브스","스포츠/드라마"),
m("legend-tc",1985,"Legend","레전드","판타지"),
m("top-gun",1986,"Top Gun","탑건","액션"),
m("color-of-money",1986,"The Color of Money","컬러 오브 머니","드라마"),
m("cocktail",1988,"Cocktail","칵테일","로맨스/드라마"),
m("rain-man",1988,"Rain Man","레인맨","드라마"),
m("born-fourth-july",1989,"Born on the Fourth of July","7월 4일생","전쟁/전기","골든글로브 남우주연"),
m("days-of-thunder",1990,"Days of Thunder","데이즈 오브 썬더","스포츠/액션"),
m("far-and-away",1992,"Far and Away","파 앤드 어웨이","로맨스/어드벤처"),
m("few-good-men",1992,"A Few Good Men","어 퓨 굿 맨","법정 드라마"),
m("the-firm",1993,"The Firm","펌","스릴러"),
m("interview-vampire",1994,"Interview with the Vampire","인터뷰 위드 뱀파이어","공포/드라마"),
m("mission-impossible",1996,"Mission: Impossible","미션 임파서블","액션"),
m("jerry-maguire",1996,"Jerry Maguire","제리 맥과이어","로맨스/드라마"),
m("eyes-wide-shut",1999,"Eyes Wide Shut","아이즈 와이드 셧","드라마/스릴러"),
m("magnolia",1999,"Magnolia","매그놀리아","드라마","오스카 남우조연 후보"),
m("mi2",2000,"Mission: Impossible 2","미션 임파서블 2","액션"),
m("vanilla-sky",2001,"Vanilla Sky","바닐라 스카이","SF/로맨스"),
m("minority-report",2002,"Minority Report","마이너리티 리포트","SF/스릴러"),
m("last-samurai",2003,"The Last Samurai","라스트 사무라이","전쟁/드라마"),
m("collateral",2004,"Collateral","콜래트럴","스릴러"),
m("war-of-worlds",2005,"War of the Worlds","우주전쟁","SF/액션"),
m("mi3",2006,"Mission: Impossible III","미션 임파서블 3","액션"),
m("lions-for-lambs",2007,"Lions for Lambs","라이언스 포 램스","드라마"),
m("tropic-thunder",2008,"Tropic Thunder","트로픽 썬더","코미디"),
m("valkyrie",2008,"Valkyrie","발키리","전쟁/스릴러"),
m("knight-and-day",2010,"Knight and Day","나이트 앤 데이","액션/코미디"),
m("mi-ghost",2011,"Mission: Impossible – Ghost Protocol","미션 임파서블: 고스트 프로토콜","액션"),
m("rock-of-ages",2012,"Rock of Ages","락 오브 에이지스","뮤지컬"),
m("jack-reacher",2012,"Jack Reacher","잭 리처","액션/스릴러"),
m("oblivion",2013,"Oblivion","오블리비언","SF/액션"),
m("edge-of-tomorrow",2014,"Edge of Tomorrow","엣지 오브 투모로우","SF/액션","일명 내일의 엣지"),
m("mi-rogue",2015,"Mission: Impossible – Rogue Nation","미션 임파서블: 로그네이션","액션"),
m("jack-reacher-2",2016,"Jack Reacher: Never Go Back","잭 리처: 네버 고 백","액션"),
m("the-mummy",2017,"The Mummy","미이라","액션/판타지"),
m("american-made",2017,"American Made","아메리칸 메이드","액션/코미디"),
m("mi-fallout",2018,"Mission: Impossible – Fallout","미션 임파서블: 폴아웃","액션"),
m("top-gun-maverick",2022,"Top Gun: Maverick","탑건: 매버릭","액션"),
m("mi-dead-reckoning",2023,"Mission: Impossible – Dead Reckoning Part One","미션 임파서블: 데드 레코닝 PART ONE","액션"),
m("mi-final-reckoning",2025,"Mission: Impossible – The Final Reckoning","미션 임파서블: 파이널 레코닝","액션"),
]

russell = [
m("prisoners-sun",1990,"Prisoners of the Sun","태양의 죄수","전쟁/드라마"),
m("the-crossing",1990,"The Crossing","크로싱","드라마"),
m("proof",1991,"Proof","프루프","드라마"),
m("spotswood",1991,"Spotswood","스폿스우드","코미디"),
m("romper-stomper",1992,"Romper Stomper","롬퍼 스톰퍼","범죄/드라마"),
m("sum-of-us",1994,"The Sum of Us","섬 오브 어스","드라마/코미디"),
m("quick-and-dead",1995,"The Quick and the Dead","퀵 앤 더 데드","서부"),
m("no-way-back",1995,"No Way Back","노 웨이 백","액션"),
m("virtuosity-rc",1995,"Virtuosity","가상현실","SF/액션"),
m("la-confidential",1997,"L.A. Confidential","엘에이 컨피덴셜","범죄/느와르"),
m("heavens-burning",1997,"Heaven's Burning","헤븐스 버닝","액션/드라마"),
m("mystery-alaska",1999,"Mystery, Alaska","미스터리 알래스카","스포츠/코미디"),
m("the-insider",1999,"The Insider","인사이더","드라마","오스카 남우주연 후보"),
m("gladiator",2000,"Gladiator","글래디에이터","역사/액션","오스카 남우주연상"),
m("proof-of-life",2000,"Proof of Life","프루프 오브 라이프","액션/스릴러"),
m("beautiful-mind",2001,"A Beautiful Mind","뷰티풀 마인드","전기/드라마","오스카 남우주연 후보"),
m("master-commander",2003,"Master and Commander: The Far Side of the World","마스터 앤드 커맨더: 위대한 정복자","전쟁/어드벤처"),
m("cinderella-man",2005,"Cinderella Man","신데렐라 맨","스포츠/드라마"),
m("good-year",2006,"A Good Year","어 굿 이어","로맨스/코미디"),
m("310-yuma",2007,"3:10 to Yuma","3:10 투 유마","서부"),
m("american-gangster-rc",2007,"American Gangster","아메리칸 갱스터","범죄/드라마"),
m("body-of-lies",2008,"Body of Lies","바디 오브 라이즈","스파이/스릴러"),
m("state-of-play",2009,"State of Play","스테이트 오브 플레이","스릴러"),
m("robin-hood",2010,"Robin Hood","로빈 후드","액션/어드벤처"),
m("next-three-days",2010,"The Next Three Days","넥스트 쓰리 데이즈","스릴러"),
m("les-miserables",2012,"Les Misérables","레미제라블","뮤지컬/드라마"),
m("broken-city",2013,"Broken City","브로큰 시티","스릴러"),
m("man-of-steel",2013,"Man of Steel","맨 오브 스틸","슈퍼히어로"),
m("winters-tale",2014,"Winter's Tale","윈터스 테일","판타지/로맨스"),
m("noah",2014,"Noah","노아","성경/드라마"),
m("water-diviner",2014,"The Water Diviner","워터 디바이너","전쟁/드라마","감독·출연"),
m("fathers-daughters",2015,"Fathers and Daughters","파더스 앤 도터스","드라마"),
m("nice-guys",2016,"The Nice Guys","나이스 가이즈","범죄/코미디"),
m("mummy-rc",2017,"The Mummy","미이라","액션/판타지"),
m("boy-erased",2018,"Boy Erased","보이 이레이즈드","드라마"),
m("unhinged",2020,"Unhinged","언힌지드","스릴러"),
m("thor-love-thunder-rc",2022,"Thor: Love and Thunder","토르: 러브 앤 썬더","슈퍼히어로"),
m("poker-face",2022,"Poker Face","포커 페이스","스릴러","감독·출연"),
m("popes-exorcist",2023,"The Pope's Exorcist","교황의 엑소시스트","공포"),
m("land-of-bad",2024,"Land of Bad","랜드 오브 배드","액션/전쟁"),
m("sleeping-dogs",2024,"Sleeping Dogs","슬리핑 독스","스릴러"),
m("the-exorcism",2024,"The Exorcism","엑소시즘","공포"),
m("kraven",2024,"Kraven the Hunter","크레이븐 더 헌터","슈퍼히어로"),
m("nuremberg",2025,"Nuremberg","뉘른베르크","역사/드라마"),
]

leo = [
m("this-boys-life",1993,"This Boy's Life","디스 보이스 라이프","드라마"),
m("whats-eating-gilbert",1993,"What's Eating Gilbert Grape","길버트 그레이프","드라마","오스카 남우조연 후보"),
m("basketball-diaries",1995,"The Basketball Diaries","농구 다이어리","드라마"),
m("total-eclipse",1995,"Total Eclipse","토탈 이클립스","전기/드라마"),
m("romeo-juliet",1996,"Romeo + Juliet","로미오와 줄리엣","로맨스"),
m("marvin-room",1996,"Marvin's Room","마빈스 룸","드라마"),
m("titanic",1997,"Titanic","타이타닉","로맨스/재난"),
m("man-iron-mask",1998,"The Man in the Iron Mask","아이언 마스크","어드벤처"),
m("celebrity-ld",1998,"Celebrity","셀러브리티","코미디"),
m("the-beach",2000,"The Beach","더 비치","어드벤처/드라마"),
m("gangs-new-york",2002,"Gangs of New York","갱스 오브 뉴욕","범죄/드라마"),
m("catch-me",2002,"Catch Me If You Can","캐치 미 이프 유 캔","범죄/코미디"),
m("the-aviator",2004,"The Aviator","에비에이터","전기/드라마","오스카 남우주연 후보"),
m("departed-ld",2006,"The Departed","디파티드","범죄/스릴러"),
m("blood-diamond",2006,"Blood Diamond","블러드 다이아몬드","어드벤처/드라마","오스카 남우주연 후보"),
m("body-of-lies-ld",2008,"Body of Lies","바디 오브 라이즈","스파이/스릴러"),
m("revolutionary-road",2008,"Revolutionary Road","레볼루셔너리 로드","드라마"),
m("shutter-island",2010,"Shutter Island","셔터 아일랜드","스릴러"),
m("inception-ld",2010,"Inception","인셉션","SF/액션"),
m("j-edgar",2011,"J. Edgar","제이 에드거","전기/드라마"),
m("django",2012,"Django Unchained","장고: 분노의 추적자","서부"),
m("great-gatsby",2013,"The Great Gatsby","위대한 개츠비","드라마/로맨스"),
m("wolf-wall-street",2013,"The Wolf of Wall Street","울프 오브 월 스트리트","범죄/코미디","오스카 남우주연 후보"),
m("the-revenant",2015,"The Revenant","레버넌트: 죽음에서 돌아온 자","어드벤처/드라마","오스카 남우주연상"),
m("once-upon-hollywood",2019,"Once Upon a Time in Hollywood","원스 어폰 어 타임 인 할리우드","코미디/드라마"),
m("dont-look-up",2021,"Don't Look Up","돈 룩 업","코미디/SF","Netflix"),
m("killers-flower-moon",2023,"Killers of the Flower Moon","플라워 킬링 문","범죄/드라마"),
m("one-battle",2025,"One Battle After Another","원 배틀 애프터 어나더","액션/드라마"),
]

matthew = [
m("dazed-confused",1993,"Dazed and Confused","데이즈드 앤 컨퓨즈드","코미디"),
m("angels-outfield",1994,"Angels in the Outfield","천사들의 경기","가족/스포츠"),
m("texas-chainsaw-next",1995,"Texas Chainsaw Massacre: The Next Generation","텍사스 전기톱 학살: 넥스트 제너레이션","공포"),
m("boys-on-side",1995,"Boys on the Side","보이즈 온 더 사이드","드라마/코미디"),
m("lone-star",1996,"Lone Star","론 스타","미스터리/드라마"),
m("time-to-kill",1996,"A Time to Kill","타임 투 킬","법정 드라마"),
m("contact",1997,"Contact","콘택트","SF/드라마"),
m("amistad",1997,"Amistad","아미스타드","역사/드라마"),
m("newton-boys",1998,"The Newton Boys","뉴턴 보이즈","범죄/드라마"),
m("edtv",1999,"EDtv","에드 TV","코미디"),
m("u-571",2000,"U-571","유-571","전쟁"),
m("wedding-planner",2001,"The Wedding Planner","웨딩 플래너","로맨스/코미디"),
m("frailty",2001,"Frailty","프레이티","스릴러/공포"),
m("reign-of-fire",2002,"Reign of Fire","레인 오브 파이어","액션/판타지"),
m("how-lose-guy",2003,"How to Lose a Guy in 10 Days","그녀를 잊는 법 10가지","로맨스/코미디"),
m("sahara",2005,"Sahara","사하라","어드벤처"),
m("two-for-money",2005,"Two for the Money","투 포 더 머니","드라마"),
m("failure-launch",2006,"Failure to Launch","페일리어 투 런치","로맨스/코미디"),
m("we-are-marshall",2006,"We Are Marshall","위 아 마셜","스포츠/드라마"),
m("fools-gold",2008,"Fool's Gold","풀스 골드","어드벤처/코미디"),
m("tropic-thunder-mm",2008,"Tropic Thunder","트로픽 썬더","코미디"),
m("ghosts-girlfriends",2009,"Ghosts of Girlfriends Past","유령 애인들","로맨스/코미디"),
m("lincoln-lawyer",2011,"The Lincoln Lawyer","링컨 변호사","법정/스릴러"),
m("bernie",2011,"Bernie","버니","코미디/드라마"),
m("killer-joe",2011,"Killer Joe","킬러 조","범죄/스릴러"),
m("mud",2012,"Mud","머드","드라마"),
m("magic-mike",2012,"Magic Mike","매직 마이크","드라마/코미디"),
m("paperboy",2012,"The Paperboy","페이퍼보이","스릴러"),
m("dallas-buyers",2013,"Dallas Buyers Club","달라스 바이어스 클럽","전기/드라마","오스카 남우주연상"),
m("wolf-wall-street-mm",2013,"The Wolf of Wall Street","울프 오브 월 스트리트","범죄/코미디"),
m("interstellar-mm",2014,"Interstellar","인터스텔라","SF"),
m("sea-of-trees",2015,"The Sea of Trees","바다의 나무","드라마"),
m("free-state-jones",2016,"Free State of Jones","프리 스테이트 오브 존스","전쟁/드라마"),
m("gold",2016,"Gold","골드","드라마"),
m("dark-tower",2017,"The Dark Tower","다크 타워","판타지/액션"),
m("white-boy-rick",2018,"White Boy Rick","화이트 보이 릭","범죄/드라마"),
m("serenity-mm",2019,"Serenity","세레니티","스릴러"),
m("beach-bum",2019,"The Beach Bum","비치 범","코미디"),
m("gentlemen",2019,"The Gentlemen","젠틀맨","범죄/코미디"),
m("rivals-amziah",2025,"The Rivals of Amziah King","아므지아 킹의 라이벌들","범죄/스릴러"),
m("lost-bus",2025,"The Lost Bus","로스트 버스","드라마/재난"),
]

tom_hardy = [
m("black-hawk-down",2001,"Black Hawk Down","블랙 호크 다운","전쟁"),
m("deserter",2002,"Deserter","디저터","전쟁/드라마"),
m("layer-cake-th",2004,"Layer Cake","레이어 케이크","범죄/스릴러"),
m("star-trek-nemesis",2002,"Star Trek: Nemesis","스타트렉: 네메시스","SF"),
m("marie-antoinette",2006,"Marie Antoinette","마리 앙투아네트","역사/드라마"),
m("stuart-a-life",2007,"Stuart: A Life Backwards","스튜어트: 어 라이프 백워즈","드라마","TV영화이나 영국 극장 공개"),
m("rocknrolla",2008,"RocknRolla","락앤롤라","범죄/코미디"),
m("bronson",2008,"Bronson","브론슨","전기/범죄"),
m("thick-as-thieves",2009,"Thick as Thieves","시크 애즈 띠브즈","범죄"),
m("inception-th",2010,"Inception","인셉션","SF/액션"),
m("warrior",2011,"Warrior","워리어","스포츠/드라마"),
m("tinker-tailor",2011,"Tinker Tailor Soldier Spy","팅커 테일러 솔저 스파이","스파이/스릴러"),
m("this-means-war",2012,"This Means War","디스 민스 워","액션/코미디"),
m("dark-knight-rises",2012,"The Dark Knight Rises","다크 나이트 라이즈","슈퍼히어로"),
m("lawless",2012,"Lawless","로리스","범죄/드라마"),
m("locke",2013,"Locke","로크","드라마"),
m("drop",2014,"The Drop","더 드롭","범죄/스릴러"),
m("mad-max-fury",2015,"Mad Max: Fury Road","매드맥스: 분노의 도로","액션"),
m("legend-th",2015,"Legend","레전드","범죄/드라마"),
m("child-44",2015,"Child 44","차일드 44","스릴러"),
m("revenant-th",2015,"The Revenant","레버넌트: 죽음에서 돌아온 자","어드벤처/드라마"),
m("dunkirk",2017,"Dunkirk","덩케르크","전쟁"),
m("venom",2018,"Venom","베놈","슈퍼히어로"),
m("capone",2020,"Capone","카포네","전기/범죄"),
m("venom-2",2021,"Venom: Let There Be Carnage","베놈 2: 렛 데어 비 카니지","슈퍼히어로"),
m("spiderhead",2022,"Spiderhead","스파이더헤드","SF/스릴러","Netflix"),
m("bikeriders",2023,"The Bikeriders","바이커라이더스","범죄/드라마"),
m("venom-3",2024,"Venom: The Last Dance","베놈: 라스트 댄스","슈퍼히어로"),
m("havoc",2025,"Havoc","헤이복","액션/스릴러","Netflix"),
]

gerard = [
m("mrs-brown",1997,"Mrs Brown","미세스 브라운","역사/드라마"),
m("tomorrow-never-dies",1997,"Tomorrow Never Dies","007 투모로우 네버 다이","액션/스파이","소역할"),
m("tale-mummy",1998,"Tale of the Mummy","테일 오브 더 미라","공포"),
m("dracula-2000",2000,"Dracula 2000","드라큘라 2000","공포"),
m("attila",2001,"Attila","아틸라","역사","미니시리즈이나 흔히 포함"),
m("reign-fire-gb",2002,"Reign of Fire","레인 오브 파이어","액션/판타지"),
m("phantom-opera",2004,"The Phantom of the Opera","오페라의 유령","뮤지컬/로맨스"),
m("tomb-raider-2",2003,"Lara Croft: Tomb Raider – The Cradle of Life","툼레이더 2: 판도라의 상자","액션"),
m("dear-frankie",2004,"Dear Frankie","디어 프랭키","드라마"),
m("beowulf-grendel",2005,"Beowulf & Grendel","베오울프 & 그렌델","액션/판타지"),
m("game-lives",2005,"The Game of Their Lives","게임 오브 데어 라이브스","스포츠"),
m("300",2006,"300","300","액션/전쟁"),
m("ps-i-love-you",2007,"P.S. I Love You","피.에스. 아이 러브 유","로맨스"),
m("butterfly-wheel",2007,"Butterfly on a Wheel","버터플라이 온 어 휠","스릴러","일명 샤터드"),
m("nim-island",2008,"Nim's Island","님의 섬","어드벤처/가족"),
m("rocknrolla-gb",2008,"RocknRolla","락앤롤라","범죄"),
m("ugly-truth",2009,"The Ugly Truth","어글리 트루스","로맨스/코미디"),
m("gamer",2009,"Gamer","게이머","SF/액션"),
m("law-abiding",2009,"Law Abiding Citizen","로 어바이딩 시티즌","스릴러"),
m("bounty-hunter",2010,"The Bounty Hunter","바운티 헌터","액션/코미디"),
m("machine-gun-preacher",2011,"Machine Gun Preacher","머신건 프리처","액션/드라마"),
m("corsican",2011,"Coriolanus","코리올라누스","드라마"),
m("playing-field",2011,"Playing for Keeps","플레잉 포 킵스","로맨스/코미디"),
m("chasing-mavericks",2012,"Chasing Mavericks","체이싱 매버릭스","스포츠/드라마"),
m("olympus-fallen",2013,"Olympus Has Fallen","화이트하우스 다운","액션"),
m("gods-egypt",2016,"Gods of Egypt","갓 오브 이집트","판타지/액션"),
m("london-fallen",2016,"London Has Fallen","런던 해즈 폴른","액션"),
m("geostorm",2017,"Geostorm","지오스톰","SF/재난"),
m("den-thieves",2018,"Den of Thieves","도둑들","범죄/액션"),
m("hunter-killer",2018,"Hunter Killer","헌터 킬러","액션/스릴러"),
m("angel-fallen",2019,"Angel Has Fallen","엔젤 해즈 폴른","액션"),
m("greenland",2020,"Greenland","그린랜드","재난/스릴러"),
m("copshop",2021,"Copshop","캅샵","액션/스릴러"),
m("last-seen-alive",2022,"Last Seen Alive","라스트 신 얼라이브","스릴러"),
m("plane",2023,"Plane","플레인","액션/스릴러"),
m("kandahar",2023,"Kandahar","칸다하르","액션/스릴러"),
m("den-thieves-2",2025,"Den of Thieves 2: Pantera","도둑들 2: 판테라","범죄/액션"),
m("greenland-2",2026,"Greenland 2: Migration","그린랜드 2: 마이그레이션","재난"),
]

charlize = [
m("2-days-valley",1996,"2 Days in the Valley","투 데이즈 인 더 밸리","범죄/스릴러"),
m("trial-error",1997,"Trial and Error","트라이얼 앤 에러","코미디"),
m("devil-advocate",1997,"The Devil's Advocate","디블스 어드보킷","스릴러"),
m("celebrity-ct",1998,"Celebrity","셀러브리티","코미디"),
m("mighty-joe",1998,"Mighty Joe Young","마이티 조 영","어드벤처"),
m("astronauts-wife",1999,"The Astronaut's Wife","아스트로넛츠 와이프","SF/스릴러"),
m("cider-house",1999,"The Cider House Rules","사이더 하우스 룰","드라마"),
m("reindeer-games",2000,"Reindeer Games","레인디어 게임즈","범죄/스릴러"),
m("legend-bagger-ct",2000,"The Legend of Bagger Vance","배거 밴스의 전설","스포츠/드라마"),
m("sweet-november",2001,"Sweet November","스위트 노벰버","로맨스"),
m("15-minutes",2001,"15 Minutes","15분","범죄/스릴러"),
m("trapped",2002,"Trapped","트랩트","스릴러"),
m("waking-life-dead",2002,"Waking Up in Reno","웨이킹 업 인 리노","코미디"),
m("italian-job",2003,"The Italian Job","이탈리안 잡","액션/범죄"),
m("monster",2003,"Monster","몬스터","전기/범죄","오스카 여우주연상"),
m("head-clouds",2004,"Head in the Clouds","헤드 인 더 클라우드","드라마/로맨스"),
m("north-country",2005,"North Country","노스 컨트리","드라마","오스카 여우주연 후보"),
m("aeon-flux",2005,"Æon Flux","이온 플럭스","SF/액션"),
m("valley-elah",2007,"In the Valley of Elah","인 더 밸리 오브 엘라","스릴러/드라마"),
m("battle-in-seattle",2007,"Battle in Seattle","배틀 인 시애틀","드라마"),
m("hancock",2008,"Hancock","핸콕","슈퍼히어로"),
m("sleepwalking",2008,"Sleepwalking","슬립워킹","드라마"),
m("the-road",2009,"The Road","더 로드","드라마/포스트아포칼립스"),
m("young-adult",2011,"Young Adult","영 어덜트","코미디/드라마"),
m("snow-white-huntsman",2012,"Snow White and the Huntsman","백설공주와 사냥꾼","판타지/액션"),
m("prometheus",2012,"Prometheus","프로메테우스","SF"),
m("million-ways",2014,"A Million Ways to Die in the West","백만 가지 방법의 웨스턴","코미디"),
m("dark-places",2015,"Dark Places","다크 플레이스","스릴러"),
m("mad-max-ct",2015,"Mad Max: Fury Road","매드맥스: 분노의 도로","액션"),
m("huntsman-winter",2016,"The Huntsman: Winter's War","헌츠맨: 윈터스 워","판타지"),
m("kubo-ct",2016,"Kubo and the Two Strings","쿠보와 전설의 악기","애니메이션","목소리"),
m("atomic-blonde",2017,"Atomic Blonde","아토믹 블론드","액션/스파이"),
m("fate-furious",2017,"The Fate of the Furious","분노의 질주: 더 익스트림","액션"),
m("tully",2018,"Tully","털리","코미디/드라마"),
m("gringo",2018,"Gringo","그링고","액션/코미디"),
m("long-shot",2019,"Long Shot","롱 샷","로맨스/코미디"),
m("bombshell",2019,"Bombshell","밤쉘: 세상을 바꾼 폭탄선언","드라마","오스카 여우주연 후보"),
m("old-guard",2020,"The Old Guard","올드 가드","액션/판타지","Netflix"),
m("f9",2021,"F9","분노의 질주: 더 얼티메이트","액션"),
m("addams-family-2",2021,"The Addams Family 2","아담스 패밀리 2","애니메이션","목소리"),
m("fast-x",2023,"Fast X","분노의 질주: 라이드 오어 다이","액션"),
m("old-guard-2",2025,"The Old Guard 2","올드 가드 2","액션/판타지","Netflix"),
]

lea = [
m("girlfriends",2006,"Girlfriends","걸프렌즈","드라마","프랑스: Mes copines"),
m("on-war",2008,"On War","온 워","드라마","프랑스: De la guerre"),
m("beautiful-person",2008,"The Beautiful Person","뷰티풀 퍼슨","드라마","프랑스: La Belle Personne · 불확실 KR"),
m("lourdes",2009,"Lourdes","루르드","드라마"),
m("belle-epine",2010,"Belle Épine","벨 에핀","드라마","불확실 KR"),
m("robin-hood-ls",2010,"Robin Hood","로빈 후드","액션"),
m("mysteries-lisbon",2010,"Mysteries of Lisbon","리스본의 미스터리","드라마"),
m("midnight-paris",2011,"Midnight in Paris","미드나잇 인 파리","로맨스/코미디"),
m("mission-impossible-gs",2011,"Mission: Impossible – Ghost Protocol","미션 임파서블: 고스트 프로토콜","액션"),
m("farewell-queen",2012,"Farewell, My Queen","여왕에게 작별을","역사/드라마"),
m("sister",2012,"Sister","시스터","드라마","프랑스: L'Enfant d'en haut"),
m("blue-warmest",2013,"Blue Is the Warmest Colour","가장 따뜻한 색","로맨스/드라마","프랑스: La Vie d'Adèle"),
m("grand-central",2013,"Grand Central","그랑 상트랄","드라마"),
m("beauty-beast",2014,"Beauty and the Beast","미녀와 야수","판타지/로맨스","프랑스판"),
m("saint-laurent",2014,"Saint Laurent","생 로랑","전기/드라마"),
m("diary-chambermaid",2015,"Diary of a Chambermaid","하녀 일기","드라마"),
m("spectre-ls",2015,"Spectre","스펙터","액션/스파이"),
m("lob",2015,"The Lobster","더 랍스터","코미디/드라마"),
m("only-end-world",2016,"It's Only the End of the World","그저 세상의 끝","드라마"),
m("course-a-suivre",2016,"Juste la fin du monde","그저 세상의 끝","드라마","중복 방지용 제외하지 않음 - same as above skip"),
m("zoe",2018,"Zoe","조이","SF/로맨스"),
m("course-vie",2018,"Kursk","쿠르스크","재난/드라마"),
m("oh-mercy",2019,"Oh Mercy!","오 메르시!","범죄/드라마","프랑스: Roubaix, une lumière"),
m("france",2021,"France","프랑스","드라마/코미디"),
m("french-dispatch",2021,"The French Dispatch","프렌치 디스패치","코미디"),
m("no-time-die-ls",2021,"No Time to Die","노 타임 투 다이","액션/스파이"),
m("crimes-future",2022,"Crimes of the Future","크라임즈 오브 더 퓨처","SF/공포"),
m("one-fine-morning",2022,"One Fine Morning","어느 멋진 아침","드라마","프랑스: Un beau matin"),
m("the-beast",2023,"The Beast","더 비스트","SF/드라마","프랑스: La Bête"),
m("dune-2",2024,"Dune: Part Two","듄: 파트 2","SF"),
]

anne = [
m("princess-diaries",2001,"The Princess Diaries","프린세스 다이어리","코미디/로맨스"),
m("other-side-heaven",2001,"The Other Side of Heaven","아더 사이드 오브 헤븐","드라마"),
m("nicholas-nickleby",2002,"Nicholas Nickleby","니콜라스 니클비","드라마"),
m("ella-enchanted",2004,"Ella Enchanted","엘라의 모험","판타지/코미디"),
m("princess-diaries-2",2004,"The Princess Diaries 2: Royal Engagement","프린세스 다이어리 2","코미디/로맨스"),
m("havoc-ah",2005,"Havoc","헤이복","드라마"),
m("brokeback",2005,"Brokeback Mountain","브로크백 마운틴","로맨스/드라마"),
m("devil-wears-prada",2006,"The Devil Wears Prada","악마는 프라다를 입는다","코미디/드라마"),
m("becoming-jane",2007,"Becoming Jane","비커밍 제인","전기/로맨스"),
m("get-smart",2008,"Get Smart","겟 스마트","액션/코미디"),
m("passengers",2008,"Passengers","패신저스","스릴러"),
m("rachel-getting",2008,"Rachel Getting Married","레이첼, 결혼하다","드라마","오스카 여우주연 후보"),
m("bride-wars",2009,"Bride Wars","브라이드 워즈","코미디"),
m("valentines-day",2010,"Valentine's Day","발렌타인 데이","로맨스/코미디"),
m("love-other-drugs",2010,"Love & Other Drugs","러브 & 드럭스","로맨스/코미디"),
m("one-day",2011,"One Day","원 데이","로맨스/드라마"),
m("dark-knight-rises-ah",2012,"The Dark Knight Rises","다크 나이트 라이즈","슈퍼히어로"),
m("les-miserables-ah",2012,"Les Misérables","레미제라블","뮤지컬/드라마","오스카 여우조연상"),
m("don-jon",2013,"Don Jon","돈 존","코미디/로맨스"),
m("interstellar-ah",2014,"Interstellar","인터스텔라","SF"),
m("song-one",2014,"Song One","송 원","드라마"),
m("intern",2015,"The Intern","인턴","코미디/드라마"),
m("alice-looking",2016,"Alice Through the Looking Glass","이상한 나라의 앨리스: 거울 나라의 앨리스","판타지"),
m("colossal",2016,"Colossal","코로설","SF/코미디"),
m("oceans-8",2018,"Ocean's 8","오션스 8","범죄/코미디"),
m("serenity-ah",2019,"Serenity","세레니티","스릴러"),
m("dark-waters",2019,"Dark Waters","다크 워터스","드라마/스릴러"),
m("last-thing-wanted",2020,"The Last Thing He Wanted","라스트 씽 히 원티드","스릴러","Netflix"),
m("locked-down",2021,"Locked Down","락드 다운","코미디/로맨스"),
m("armageddon-time",2022,"Armageddon Time","아마겟돈 타임","드라마"),
m("eileen",2023,"Eileen","아일린","스릴러/드라마"),
m("mothers-instinct",2024,"Mothers' Instinct","마더스 인스팅트","스릴러"),
m("idea-you",2024,"The Idea of You","아이디어 오브 유","로맨스","Amazon"),
]

margot = [
m("about-time",2013,"About Time","어바웃 타임","로맨스/코미디"),
m("wolf-wall-street-mr",2013,"The Wolf of Wall Street","울프 오브 월 스트리트","범죄/코미디"),
m("suite-francaise",2014,"Suite Française","수트 프랑세즈","전쟁/로맨스"),
m("focus",2015,"Focus","포커스","범죄/코미디"),
m("z-zachariah",2015,"Z for Zachariah","Z를 위하여","SF/드라마"),
m("whiskey-tango",2016,"Whiskey Tango Foxtrot","위스키 탱고 폭스트롯","전쟁/코미디"),
m("legend-tarzan",2016,"The Legend of Tarzan","전설의 타잔","어드벤처"),
m("suicide-squad",2016,"Suicide Squad","수어사이드 스쿼드","슈퍼히어로"),
m("i-tonya",2017,"I, Tonya","아이, 토냐","전기/드라마","오스카 여우주연 후보"),
m("goodbye-christopher",2017,"Goodbye Christopher Robin","굿바이 크리스토퍼 로빈","전기/드라마"),
m("mary-queen",2018,"Mary Queen of Scots","메리 퀸 오브 스코츠","역사/드라마"),
m("terminal",2018,"Terminal","터미널","스릴러"),
m("once-upon-mr",2019,"Once Upon a Time in Hollywood","원스 어폰 어 타임 인 할리우드","코미디/드라마"),
m("bombshell-mr",2019,"Bombshell","밤쉘: 세상을 바꾼 폭탄선언","드라마"),
m("birds-of-prey",2020,"Birds of Prey","버즈 오브 프레이","슈퍼히어로/액션"),
m("dreamland",2020,"Dreamland","드림랜드","범죄/드라마"),
m("tss",2021,"The Suicide Squad","더 수어사이드 스쿼드","슈퍼히어로"),
m("amsterdam",2022,"Amsterdam","암스테르담","코미디/미스터리"),
m("babylon",2022,"Babylon","바빌론","코미디/드라마"),
m("asteroid-city",2023,"Asteroid City","애스터로이드 시티","코미디/드라마"),
m("barbie",2023,"Barbie","바비","코미디/판타지"),
m("my-old-ass",2024,"My Old Ass","마이 올드 애스","코미디/드라마","카메오·제작"),
]

# Fix lea duplicate
lea = [x for x in lea if x["id"] != "course-a-suivre"]

actors = [
  {"id":"denzel","nameKo":"덴젤 워싱턴","nameEn":"Denzel Washington","movies":denzel},
  {"id":"matt","nameKo":"맷 데이먼","nameEn":"Matt Damon","movies":matt},
  {"id":"daniel","nameKo":"다니엘 크레이그","nameEn":"Daniel Craig","movies":daniel},
  {"id":"tomcruise","nameKo":"톰 크루즈","nameEn":"Tom Cruise","movies":tom_cruise},
  {"id":"russell","nameKo":"러셀 크로우","nameEn":"Russell Crowe","movies":russell},
  {"id":"leo","nameKo":"레오나르도 디카프리오","nameEn":"Leonardo DiCaprio","movies":leo},
  {"id":"matthew","nameKo":"매튜 맥커너히","nameEn":"Matthew McConaughey","movies":matthew},
  {"id":"tomhardy","nameKo":"톰 하디","nameEn":"Tom Hardy","movies":tom_hardy},
  {"id":"gerard","nameKo":"제라드 버틀러","nameEn":"Gerard Butler","movies":gerard},
  {"id":"charlize","nameKo":"샤를리즈 테론","nameEn":"Charlize Theron","movies":charlize},
  {"id":"lea","nameKo":"레아 세이두","nameEn":"Léa Seydoux","movies":lea},
  {"id":"anne","nameKo":"앤 해서웨이","nameEn":"Anne Hathaway","movies":anne},
  {"id":"margot","nameKo":"마고 로비","nameEn":"Margot Robbie","movies":margot},
]

# Remove Attila from Gerard (TV miniseries)
gerard[:] = [x for x in gerard if x["id"] != "attila"]
# Remove stuart TV if preferred - keep as note says TV
tom_hardy[:] = [x for x in tom_hardy if x["id"] != "stuart-a-life"]

uncertain = [
  "Léa Seydoux: The Beautiful Person / Belle Épine — 한국 개봉명 불확실",
  "Gerard Butler: Butterfly on a Wheel — 한국명 '샤터드'로도 표기",
  "Tom Hardy: Thick as Thieves — 한국 개봉명 불확실 (시크 애즈 띠브즈)",
  "Russell Crowe: Prisoners of the Sun — 일명 Blood Oath",
  "Matt Damon: Glory Daze 등 초기 소작 일부 제외",
]

out = {
  "version": 1,
  "storageKey": "movie-checklist-v1",
  "actors": actors,
  "uncertainTitles": uncertain,
}

with open("/workspace/movie-checklist/movies-data.js", "w", encoding="utf-8") as f:
    f.write("window.MOVIE_CHECKLIST_DATA = ")
    f.write(json.dumps(out, ensure_ascii=False, indent=2))
    f.write(";\n")

# counts
print("Actor counts:")
total=0
for a in actors:
    n=len(a["movies"])
    total+=n
    print(f"  {a['nameKo']}: {n}")
print(f"TOTAL: {total}")
